### ISSUE TITLE
Apng fails to render with versions newer then 2.23.0

### ISSUE THREAD

**Issue by connyduck** [penfeizhou/APNG4Android#188]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      
| ---------------------------- | ----------------------------------------------------- | 
| Device Info                  | probably all, tried with a Fairphone 4                               |      
| System Version               | probably all, tried with Android 12                                             |      
| APNG4Android Library Version | 2.25.0                                           |      
| Repro rate                   | 90%   |      
| Repro with our demo project  | no, but we have quite a custom setup that loads the images into TextViews as Spans            |     |
| Demo project link            |  relevant code is [here](https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/java/com/keylesspalace/tusky/util/CustomEmojiHelper.kt)|      

### Issue Description and Steps

[This apng](https://corteximplant.com/system/custom_emojis/images/000/008/957/original/615c700c048a5e4b.png) fails to load on version 2.24.0 and 2.25.0. The console is spammed with `FrameAnimationDrawable onRender:Buffer not large enough for pixels`. When I tell Glide to load the image with smaller dimensions, it renders, but has completely wrong dimensions. Screenshots and additional info can be found in our issue: https://github.com/tuskyapp/Tusky/issues/3631

When I downgrade to 2.23.0, it works just fine.

**Comment by jingpeng** [comment]
https://github.com/penfeizhou/APNG4Android/assets/5223226/29e8244a-d42d-4324-a4ab-35c39425fa50

**Comment by jingpeng** [comment]
I use latest code to animate this image, it seems to work normally

**Comment by nikclayton** [comment]
Sorry, this isn't fixed in 2.26.0, I still see this same problem in Tusky.

It's tricky to track down because I can't easily build APNG4Android locally (I'll file a separate issue for that with more details), but I've tracked this down to a difference in the bitmap sizes in `APNGFrame.onDraw()`.

In 2.23.0 (which works), if I debug `onDraw()` the dimensions of `bitmap` when loading this APNG are 64 x 64 x 32bpp = 16K. That matches the size of the buffer that `FrameAnimationDrawable.onRender()` uses, so there is no error.

In 2.24.0 and above (which doesn't work) the dimensions of `bitmap` are 128 x 128 x 32bpp = 64K. That's four times larger than the size of the `FrameAnimationDrawable.onRender()` buffer, so it fails.

The native dimensions of the source PNG file are 128 x 128 x 32bpp.

**Comment by nikclayton** [comment]
@jingpeng 

https://github.com/penfeizhou/APNG4Android/commit/e8f8fd3a5a9dfffe6151b922a76a61edd0a3609c is the problematic commit.

If I revert that then Tusky displays the animated PNG correctly.

That commit was to fix https://github.com/penfeizhou/APNG4Android/issues/165

Tusky's code to get and display the animated PNG is https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/java/com/keylesspalace/tusky/util/CustomEmojiHelper.kt.

The image is being loaded in to a drawable that will be displayed as a Span. The Span (`EmojiSpan` in our code) contains code to adjust the size of the image so that it fits within the line height of the span and maintains its aspect ratio.

I'll keep looking...

**Comment by jingpeng** [comment]
Can you provide me a demo project with the related images?

**Comment by jingpeng** [comment]
I think you should not mannually call setBounds or trigger it at any time, like this issue: #182 . Inappropriate call or invoke on it may cause issue

**Comment by nikclayton** [comment]
Yes, calling `setBounds` will cause a problem, because of this race condition.

But the race condition didn't exist in 2.23.0.

And expecting to be able to call `setBounds` on a drawable seems like a reasonable thing to do. Especially for emoji -- the emoji should match the text height, whatever the user might have set that to.

The problem this was supposed to fix was described in https://github.com/penfeizhou/APNG4Android/issues/165.

Unfortunately, Google Translate is not providing enough information that I can understand the original problem, and why changing `sampleSize` in a `Runnable` was the necessary fix.

If you could explain the original problem from #165 I might be able to suggest an alternative fix that doesn't have this race condition.

**Comment by connyduck** [comment]
This is still a problem for us @jingpeng
